export type AIModelCategory = "script" | "text" | "image" | "video" | "avatar"
export type AIProviderSlug =
  | "nextapi"
  | "openai"
  | "anthropic"
  | "google"
  | "byteplus"
  | "deepseek"
  | "qwen"
  | "glm"
  | "kimi"
  | "minimax"
  | "black-forest"
  | "kuaishou"

export type AIModelCatalogItem = {
  id: string
  category: AIModelCategory
  name: string
  provider: string
  providerSlug: AIProviderSlug
  icon: string
  enabled: boolean
  status?: "live" | "configured" | "compat" | "coming_soon"
  tier?: "primary" | "advanced" | "economy" | "experimental" | "compat"
  capabilities?: Array<"script" | "storyboard" | "vision" | "image" | "video" | "avatar" | "fast" | "quality" | "long_context">
  description: string
}

export const AI_MODEL_CATALOG: AIModelCatalogItem[] = [
  {
    id: "script-director-default",
    category: "script",
    name: "Director Script Planner",
    provider: "NextAPI",
    providerSlug: "nextapi",
    icon: "S",
    enabled: false,
    status: "coming_soon",
    tier: "primary",
    capabilities: ["script", "storyboard"],
    description: "Staged script planning model. Operators can enable it after a script provider is configured.",
  },
  {
    id: "gpt-5.5",
    category: "text",
    name: "GPT-5.5",
    provider: "OpenAI",
    providerSlug: "openai",
    icon: "T",
    enabled: false,
    status: "coming_soon",
    tier: "advanced",
    capabilities: ["script", "storyboard", "quality"],
    description: "Flagship OpenAI text/reasoning slot. Enable when your API account has access.",
  },
  {
    id: "gpt-5.4",
    category: "text",
    name: "GPT-5.4",
    provider: "OpenAI",
    providerSlug: "openai",
    icon: "T",
    enabled: false,
    status: "coming_soon",
    tier: "advanced",
    capabilities: ["script", "storyboard", "quality"],
    description: "Advanced OpenAI text/reasoning slot. Enable when your API account has access.",
  },
  {
    id: "gpt-4.1",
    category: "text",
    name: "GPT-4.1",
    provider: "OpenAI",
    providerSlug: "openai",
    icon: "T",
    enabled: false,
    status: "coming_soon",
    tier: "primary",
    capabilities: ["script", "storyboard"],
    description: "OpenAI-compatible script and planning model.",
  },
  {
    id: "seed-1.6",
    category: "text",
    name: "Seed 1.6",
    provider: "BytePlus",
    providerSlug: "byteplus",
    icon: "T",
    enabled: false,
    status: "coming_soon",
    tier: "primary",
    capabilities: ["script", "storyboard", "long_context"],
    description: "BytePlus text model for story, script, and shot planning. Enable after a text provider is configured.",
  },
  {
    id: "seed-1.8",
    category: "text",
    name: "Seed 1.8",
    provider: "BytePlus",
    providerSlug: "byteplus",
    icon: "T",
    enabled: false,
    status: "coming_soon",
    tier: "primary",
    capabilities: ["script", "storyboard", "long_context"],
    description: "Long-context BytePlus text model placeholder for Director planning.",
  },
  {
    id: "claude-opus-4.5",
    category: "text",
    name: "Claude Opus 4.5",
    provider: "Anthropic",
    providerSlug: "anthropic",
    icon: "T",
    enabled: false,
    status: "coming_soon",
    tier: "advanced",
    capabilities: ["script", "storyboard", "quality"],
    description: "High-quality writing and planning model via Anthropic Messages API.",
  },
  {
    id: "claude-sonnet-4.5",
    category: "text",
    name: "Claude Sonnet 4.5",
    provider: "Anthropic",
    providerSlug: "anthropic",
    icon: "T",
    enabled: false,
    status: "coming_soon",
    tier: "primary",
    capabilities: ["script", "storyboard", "fast"],
    description: "Balanced writing, coding, and planning model via Anthropic Messages API.",
  },
  {
    id: "gemini-2.5-pro",
    category: "text",
    name: "Gemini 2.5 Pro",
    provider: "Google",
    providerSlug: "google",
    icon: "T",
    enabled: false,
    status: "coming_soon",
    tier: "primary",
    capabilities: ["script", "storyboard", "long_context"],
    description: "Google text and multimodal planning model through OpenAI-compatible API.",
  },
  {
    id: "gemini-2.5-flash",
    category: "text",
    name: "Gemini 2.5 Flash",
    provider: "Google",
    providerSlug: "google",
    icon: "T",
    enabled: false,
    status: "coming_soon",
    tier: "economy",
    capabilities: ["script", "storyboard", "fast"],
    description: "Fast Google planning model through OpenAI-compatible API.",
  },
  {
    id: "qwen-plus",
    category: "text",
    name: "Qwen Plus",
    provider: "Alibaba",
    providerSlug: "qwen",
    icon: "T",
    enabled: false,
    status: "coming_soon",
    tier: "primary",
    capabilities: ["script", "storyboard"],
    description: "DashScope OpenAI-compatible model for Chinese script and production copy.",
  },
  {
    id: "qwen-max",
    category: "text",
    name: "Qwen Max",
    provider: "Alibaba",
    providerSlug: "qwen",
    icon: "T",
    enabled: false,
    status: "coming_soon",
    tier: "advanced",
    capabilities: ["script", "storyboard", "quality"],
    description: "Higher-quality Qwen text model slot.",
  },
  {
    id: "glm-4.6",
    category: "text",
    name: "GLM-4.6",
    provider: "Zhipu",
    providerSlug: "glm",
    icon: "T",
    enabled: false,
    status: "coming_soon",
    tier: "primary",
    capabilities: ["script", "storyboard"],
    description: "Zhipu OpenAI-compatible text model.",
  },
  {
    id: "kimi-k2",
    category: "text",
    name: "Kimi K2",
    provider: "Moonshot",
    providerSlug: "kimi",
    icon: "T",
    enabled: false,
    status: "coming_soon",
    tier: "primary",
    capabilities: ["script", "storyboard", "long_context"],
    description: "Kimi/Moonshot long-context writing model.",
  },
  {
    id: "MiniMax-M1",
    category: "text",
    name: "MiniMax M1",
    provider: "MiniMax",
    providerSlug: "minimax",
    icon: "T",
    enabled: false,
    status: "coming_soon",
    tier: "primary",
    capabilities: ["script", "storyboard"],
    description: "MiniMax text model slot for script and planning.",
  },
  {
    id: "deepseek-chat",
    category: "text",
    name: "DeepSeek Chat",
    provider: "DeepSeek",
    providerSlug: "deepseek",
    icon: "T",
    enabled: false,
    status: "coming_soon",
    tier: "economy",
    capabilities: ["script", "storyboard", "fast"],
    description: "Text/storyboard model placeholder. Configure a default text provider in admin to use AI Director.",
  },
  {
    id: "gpt-4o-mini",
    category: "text",
    name: "GPT-4o mini",
    provider: "OpenAI",
    providerSlug: "openai",
    icon: "T",
    enabled: false,
    status: "coming_soon",
    tier: "economy",
    capabilities: ["script", "storyboard", "fast"],
    description: "OpenAI-compatible text model placeholder.",
  },
  {
    id: "gpt-image-2",
    category: "image",
    name: "GPT Image 2",
    provider: "OpenAI",
    providerSlug: "openai",
    icon: "I",
    enabled: false,
    status: "coming_soon",
    tier: "advanced",
    capabilities: ["image", "quality"],
    description: "OpenAI image generation slot. Enable when your API account has access.",
  },
  {
    id: "gpt-image-1.5",
    category: "image",
    name: "GPT Image 1.5",
    provider: "OpenAI",
    providerSlug: "openai",
    icon: "I",
    enabled: false,
    status: "coming_soon",
    tier: "primary",
    capabilities: ["image"],
    description: "OpenAI image generation slot. Enable when your API account has access.",
  },
  {
    id: "gpt-image-1",
    category: "image",
    name: "GPT Image 1",
    provider: "OpenAI",
    providerSlug: "openai",
    icon: "I",
    enabled: false,
    status: "coming_soon",
    tier: "compat",
    capabilities: ["image"],
    description: "OpenAI image generation compatibility model.",
  },
  {
    id: "gemini-2.5-flash-image",
    category: "image",
    name: "Gemini Image / Nano Banana",
    provider: "Google",
    providerSlug: "google",
    icon: "I",
    enabled: false,
    status: "coming_soon",
    tier: "primary",
    capabilities: ["image", "fast"],
    description: "Google image-generation slot commonly referred to as Nano Banana.",
  },
  {
    id: "flux-kontext",
    category: "image",
    name: "FLUX Kontext",
    provider: "Black Forest Labs",
    providerSlug: "black-forest",
    icon: "I",
    enabled: false,
    status: "coming_soon",
    tier: "primary",
    capabilities: ["image"],
    description: "Reference image generation placeholder. Enable after an image provider key is configured.",
  },
  {
    id: "seedream-4.0",
    category: "image",
    name: "Seedream 4.0",
    provider: "BytePlus",
    providerSlug: "byteplus",
    icon: "I",
    enabled: false,
    status: "coming_soon",
    tier: "primary",
    capabilities: ["image"],
    description: "BytePlus image generation model. Intended for storyboard references and asset generation.",
  },
  {
    id: "seedream-4.5",
    category: "image",
    name: "Seedream 4.5",
    provider: "BytePlus",
    providerSlug: "byteplus",
    icon: "I",
    enabled: false,
    status: "coming_soon",
    tier: "advanced",
    capabilities: ["image", "quality"],
    description: "Higher-quality BytePlus image generation model placeholder.",
  },
  {
    id: "seedream-5.0-lite",
    category: "image",
    name: "Seedream 5.0 Lite",
    provider: "BytePlus",
    providerSlug: "byteplus",
    icon: "I",
    enabled: false,
    status: "coming_soon",
    tier: "economy",
    capabilities: ["image", "fast"],
    description: "Lite BytePlus image model placeholder for lower-cost storyboard references.",
  },
  {
    id: "qwen-image",
    category: "image",
    name: "Qwen Image",
    provider: "Alibaba",
    providerSlug: "qwen",
    icon: "I",
    enabled: false,
    status: "coming_soon",
    tier: "primary",
    capabilities: ["image"],
    description: "DashScope image-generation slot for visual references.",
  },
  {
    id: "cogview-4",
    category: "image",
    name: "CogView 4",
    provider: "Zhipu",
    providerSlug: "glm",
    icon: "I",
    enabled: false,
    status: "coming_soon",
    tier: "primary",
    capabilities: ["image"],
    description: "Zhipu image-generation slot.",
  },
  {
    id: "seedance-2.0-pro",
    category: "video",
    name: "Seedance 2.0 Pro",
    provider: "BytePlus",
    providerSlug: "byteplus",
    icon: "V",
    enabled: true,
    status: "live",
    tier: "primary",
    capabilities: ["video", "quality"],
    description: "Live video model routed through the existing NextAPI video task and credit system.",
  },
  {
    id: "seedance-2.0-fast",
    category: "video",
    name: "Seedance 2.0 Fast",
    provider: "BytePlus",
    providerSlug: "byteplus",
    icon: "V",
    enabled: true,
    status: "live",
    tier: "economy",
    capabilities: ["video", "fast"],
    description: "Fast Seedance 2.0 tier routed through the existing NextAPI video task and credit system.",
  },
  {
    id: "seedance-1.5-pro",
    category: "video",
    name: "Seedance 1.5 Pro",
    provider: "BytePlus",
    providerSlug: "byteplus",
    icon: "V",
    enabled: true,
    status: "compat",
    tier: "compat",
    capabilities: ["video"],
    description: "Compatibility public ID. Routed by provider mapping to the configured Seedance upstream.",
  },
  {
    id: "seedance-1.0-pro",
    category: "video",
    name: "Seedance 1.0 Pro",
    provider: "BytePlus",
    providerSlug: "byteplus",
    icon: "V",
    enabled: true,
    status: "compat",
    tier: "compat",
    capabilities: ["video"],
    description: "Compatibility public ID. Routed by provider mapping to the configured Seedance upstream.",
  },
  {
    id: "seedance-1.0-pro-fast",
    category: "video",
    name: "Seedance 1.0 Pro Fast",
    provider: "BytePlus",
    providerSlug: "byteplus",
    icon: "V",
    enabled: true,
    status: "compat",
    tier: "compat",
    capabilities: ["video", "fast"],
    description: "Compatibility fast public ID. Routed by provider mapping to the configured Seedance upstream.",
  },
  {
    id: "video-01",
    category: "video",
    name: "MiniMax Video-01",
    provider: "MiniMax",
    providerSlug: "minimax",
    icon: "V",
    enabled: false,
    status: "coming_soon",
    tier: "primary",
    capabilities: ["video"],
    description: "MiniMax video slot. Requires a dedicated video provider adapter before live use.",
  },
  {
    id: "kling-video",
    category: "video",
    name: "Kling Video",
    provider: "Kuaishou",
    providerSlug: "kuaishou",
    icon: "V",
    enabled: false,
    status: "coming_soon",
    tier: "primary",
    capabilities: ["video"],
    description: "Video model placeholder. Not available until an operator configures a live provider.",
  },
  {
    id: "omnihuman-1.5",
    category: "avatar",
    name: "OmniHuman 1.5",
    provider: "BytePlus",
    providerSlug: "byteplus",
    icon: "A",
    enabled: false,
    status: "coming_soon",
    tier: "advanced",
    capabilities: ["avatar", "video"],
    description: "Digital human slot for future avatar workflows.",
  },
  {
    id: "omnihuman-1.0",
    category: "avatar",
    name: "OmniHuman 1.0",
    provider: "BytePlus",
    providerSlug: "byteplus",
    icon: "A",
    enabled: false,
    status: "coming_soon",
    tier: "compat",
    capabilities: ["avatar", "video"],
    description: "Digital human compatibility slot for future avatar workflows.",
  },
]
