import type { WorkflowTemplate } from "@/stores/director-store";

export const TEMPLATE_CATALOG: WorkflowTemplate[] = [
  {
    id: "tmpl_product_launch_30s",
    name: "Product Launch Hero 30s",
    nameZh: "产品首发广告 30s",
    category: "system",
    description: "从痛点、产品揭示、材质特写到场景验证和 CTA 的完整商品广告链路。",
    duration: "30s",
    shotCount: 8,
    shotDuration: 5,
    aspectRatio: "16:9",
    style: "premium commercial, clean studio lighting, precise product macro, restrained purple cyan accent",
    workflow: "image_to_video",
    prompt:
      "为一款即将发布的高端智能硬件制作 30 秒产品首发广告。结构：1 痛点环境中创作者受阻，2 产品轮廓被自然光揭示，3 材质和按键微距特写，4 用户拿起产品开始操作，5 核心功能以清晰画面演示，6 产品进入真实使用场景，7 结果画面对比展示价值，8 品牌收束与 CTA。每个镜头只保留一个动作；需要 Reference Stack 锁定产品外观，Camera Motion 使用慢推、环绕和稳定跟拍，生成前检查产品一致性、文字溢出、镜头时长和垫图传参。",
    tags: ["产品", "广告", "首发", "垫图"],
    thumbnail: "/templates/product-launch.jpg",
    difficulty: "进阶",
    deliverables: ["分镜图", "首尾帧", "产品垫图", "30s 时间线"],
    chain: ["Brief", "Reference Stack", "Prompt Strategy", "Camera Motion", "Preflight"],
    variables: ["产品名", "目标用户", "核心卖点", "品牌调性"],
  },
  {
    id: "tmpl_ugc_unboxing_20s",
    name: "UGC Unboxing 20s",
    nameZh: "达人开箱种草 20s",
    category: "system",
    description: "适合小红书、TikTok、Reels 的轻量开箱：真实手部动作、卖点字幕和自然口播。",
    duration: "20s",
    shotCount: 7,
    shotDuration: 4,
    aspectRatio: "9:16",
    style: "bright UGC product video, handheld but stable, authentic creator desk, soft daylight",
    workflow: "image_to_video",
    prompt:
      "制作一支 20 秒竖屏达人开箱短片。结构：1 包裹进入画面制造期待，2 拆开包装露出产品，3 手部展示关键细节，4 第一次使用的真实反应，5 对比旧方案或痛点，6 三个卖点快速节奏展示，7 桌面定格和购买理由。要求镜头自然但不晃，产品外观由参考图锁定；对白和字幕要口语化，不要夸张营销腔；每个 shot 自动继承产品垫图。",
    tags: ["UGC", "开箱", "竖屏", "电商"],
    thumbnail: "/templates/ugc-unboxing.jpg",
    difficulty: "入门",
    deliverables: ["口播提纲", "卖点字幕", "产品特写", "竖屏时间线"],
    chain: ["Brief", "Shot Decomposition", "Reference Stack", "Subtitle", "Timeline"],
    variables: ["产品类型", "价格带", "卖点", "平台"],
  },
  {
    id: "tmpl_travel_vlog_45s",
    name: "Travel Vlog 45s",
    nameZh: "旅行 Vlog 45s",
    category: "system",
    description: "抵达、环境、人物体验、当地细节和日落收束的旅行叙事模板。",
    duration: "45s",
    shotCount: 10,
    shotDuration: 5,
    aspectRatio: "16:9",
    style: "cinematic travel vlog, natural color, gentle handheld movement, warm documentary feeling",
    workflow: "text_to_video",
    prompt:
      "制作 45 秒旅行 vlog：从抵达目的地开始，逐步展示街道、海岸、当地食物、人物体验、交通移动、情绪高潮和日落收束。每个镜头一个清晰动作，Camera Motion 以稳定手持、慢推和轻微横移为主；Prompt Decomposition 输出 first frame 和 last frame；Timeline 需要音乐节奏点和字幕标记。",
    tags: ["旅行", "Vlog", "生活方式", "分镜"],
    thumbnail: "/templates/travel-vlog.jpg",
    difficulty: "入门",
    deliverables: ["10 镜头分镜", "音乐节奏点", "字幕标记", "旅行氛围 prompt"],
    chain: ["Brief", "Scene Group", "Storyboard", "Camera Motion", "Timeline"],
    variables: ["地点", "人物", "旅行主题", "音乐情绪"],
  },
  {
    id: "tmpl_saas_feature_demo_30s",
    name: "SaaS Feature Demo 30s",
    nameZh: "SaaS 功能演示 30s",
    category: "system",
    description: "把界面、结果和价值证明拆成清晰的产品演示镜头，适合官网和发布会。",
    duration: "30s",
    shotCount: 8,
    shotDuration: 5,
    aspectRatio: "16:9",
    style: "modern SaaS product film, polished interface closeups, clean white background, precise motion graphics",
    workflow: "multimodal_story",
    prompt:
      "为一款 AI 创作 SaaS 制作 30 秒功能演示。结构：1 用户目标，2 旧流程低效，3 输入 brief，4 Storyflow 自动拆解，5 参考素材和镜头语言联动，6 时间线生成，7 预览结果，8 团队交付。界面素材作为 reference video 或 image 传入，所有 UI 镜头保持可读但不堆字；提示词避免把 UI 文案塞进画面生成。",
    tags: ["SaaS", "功能演示", "发布", "界面"],
    thumbnail: "/templates/saas-explainer.jpg",
    difficulty: "专业",
    deliverables: ["功能脚本", "界面镜头", "结果对比", "发布版时间线"],
    chain: ["Brief", "Prompt Decomposition", "Reference Stack", "Storyboard", "Output"],
    variables: ["产品名", "功能名", "目标用户", "交付渠道"],
  },
  {
    id: "tmpl_short_drama_hook_35s",
    name: "Short Drama Hook 35s",
    nameZh: "短剧强钩子 35s",
    category: "system",
    description: "适合竖屏剧情：开场冲突、角色关系、反转和悬念收束。",
    duration: "35s",
    shotCount: 9,
    shotDuration: 4,
    aspectRatio: "9:16",
    style: "vertical cinematic drama, expressive closeups, controlled handheld, high emotional tension",
    workflow: "multimodal_story",
    prompt:
      "生成一支 35 秒竖屏短剧预告。结构：1 三秒内给出冲突，2 主角反应特写，3 对手提出压力，4 关键物件或信息出现，5 关系反转，6 快速交叉剪辑，7 情绪爆发，8 悬念停顿，9 留下下一集问题。必须先抽取角色锚点，再生成角色三视图和表情参考；每个 shot 继承 Identity Lock，并在 Preflight 阻断角色漂移。",
    tags: ["短剧", "角色一致性", "剧情", "竖屏"],
    thumbnail: "/templates/short-drama.jpg",
    difficulty: "专业",
    deliverables: ["角色锚点", "表情参考", "剧情节拍", "悬念结尾"],
    chain: ["Character Extractor", "Identity Lock", "Storyboard", "Timeline", "Quality Check"],
    variables: ["主角", "冲突", "反转", "结尾悬念"],
  },
  {
    id: "tmpl_food_reel_18s",
    name: "Food Reel 18s",
    nameZh: "美食探店 18s",
    category: "system",
    description: "菜品微距、出餐动作、环境氛围和最终一口的短视频模板。",
    duration: "18s",
    shotCount: 6,
    shotDuration: 4,
    aspectRatio: "9:16",
    style: "premium food reel, appetizing macro, soft steam, warm clean lighting, crisp ingredient texture",
    workflow: "image_to_video",
    prompt:
      "为一家餐厅制作 18 秒美食探店短视频。结构：1 门店或桌面氛围，2 厨师出餐动作，3 菜品冒热气微距，4 酱汁或食材细节，5 人物试吃反应，6 最终菜单或招牌菜收束。需要菜品参考图作为 image_urls；Camera Motion 使用微距慢推、俯拍和稳定横移；不要让字幕压住菜品主体。",
    tags: ["美食", "探店", "竖屏", "微距"],
    thumbnail: "/templates/food-reel.jpg",
    difficulty: "入门",
    deliverables: ["菜品分镜", "微距镜头", "字幕节奏", "封面帧"],
    chain: ["Reference Stack", "Storyboard", "Camera Motion", "Subtitle", "Output"],
    variables: ["餐厅名", "招牌菜", "价格带", "城市"],
  },
  {
    id: "tmpl_brand_manifesto_45s",
    name: "Brand Manifesto 45s",
    nameZh: "品牌宣言片 45s",
    category: "system",
    description: "用于品牌升级、融资路演或发布会开场的高质感叙事片。",
    duration: "45s",
    shotCount: 11,
    shotDuration: 5,
    aspectRatio: "16:9",
    style: "cinematic brand film, quiet confidence, elegant negative space, refined camera movement",
    workflow: "multimodal_story",
    prompt:
      "制作 45 秒品牌宣言片。结构：1 时代背景和用户问题，2 团队/用户真实瞬间，3 产品或服务如何介入，4 三个价值主张，每个价值只用一个视觉隐喻，5 结果画面，6 品牌收束。参考素材可包含品牌色、产品界面、人物素材和 logo，但生成画面不要伪造不可控文字；用 Prompt Strategy 把文案和画面分离。",
    tags: ["品牌", "宣言片", "发布会", "团队"],
    thumbnail: "/templates/saas-explainer.jpg",
    difficulty: "专业",
    deliverables: ["品牌叙事", "镜头语言", "参考资产策略", "发布会版本"],
    chain: ["Production Bible", "Reference Stack", "Storyboard", "Review", "Version"],
    variables: ["品牌名", "用户问题", "价值主张", "发布场景"],
  },
  {
    id: "tmpl_real_estate_flythrough_20s",
    name: "Real Estate Flythrough 20s",
    nameZh: "高端空间漫游 20s",
    category: "system",
    description: "酒店、民宿、展厅和样板间的空间动线展示。",
    duration: "20s",
    shotCount: 6,
    shotDuration: 5,
    aspectRatio: "16:9",
    style: "architectural film, smooth gimbal and drone movement, natural sunset light, premium interior",
    workflow: "text_to_video",
    prompt:
      "制作 20 秒高端空间漫游。结构：1 外立面建立空间，2 入口推进，3 客厅或主空间横移，4 细节材质特写，5 窗景或景观，6 结束在最具记忆点的位置。Camera Motion 必须稳定，不使用过快 FPV；如果有实拍参考图，作为空间风格和材质垫图传入。",
    tags: ["空间", "房产", "酒店", "运镜"],
    thumbnail: "/templates/travel-vlog.jpg",
    difficulty: "进阶",
    deliverables: ["空间动线", "材质特写", "稳定运镜", "交付封面"],
    chain: ["Scene Group", "Reference Stack", "Camera Motion", "Timeline"],
    variables: ["空间类型", "面积", "亮点", "目标客群"],
  },
  {
    id: "tmpl_automotive_showcase_15s",
    name: "Automotive Showcase 15s",
    nameZh: "汽车动态展示 15s",
    category: "system",
    description: "适合新车、改装车和品牌社媒的动静结合展示。",
    duration: "15s",
    shotCount: 5,
    shotDuration: 4,
    aspectRatio: "16:9",
    style: "automotive commercial, glossy reflections, controlled tracking shot, premium dusk lighting",
    workflow: "image_to_video",
    prompt:
      "制作 15 秒汽车动态展示：1 车身轮廓从暗处显现，2 前脸和灯组特写，3 车轮启动和路面细节，4 海岸公路稳定跟拍，5 停车定格展示品牌气质。必须使用车辆参考图锁定外观，禁止让车标和车身比例漂移；生成前检查 image_urls 是否传入。",
    tags: ["汽车", "广告", "产品一致性"],
    thumbnail: "/templates/product-launch.jpg",
    difficulty: "进阶",
    deliverables: ["车辆垫图", "动态镜头", "品牌定格", "质量检查"],
    chain: ["Reference Stack", "Identity Lock", "Camera Motion", "Preflight"],
    variables: ["车型", "场景", "卖点", "品牌气质"],
  },
  {
    id: "tmpl_ai_influencer_vlog_30s",
    name: "AI Influencer Vlog 30s",
    nameZh: "虚拟达人日常 30s",
    category: "system",
    description: "强调角色资产继承、表情变化和服装一致性的达人短片。",
    duration: "30s",
    shotCount: 8,
    shotDuration: 4,
    aspectRatio: "9:16",
    style: "creator vlog, realistic character consistency, soft city daylight, handheld selfie rhythm",
    workflow: "multimodal_story",
    prompt:
      "生成 30 秒虚拟达人日常 vlog：1 角色对镜头打招呼，2 城市街道行走，3 咖啡店点单，4 展示当天穿搭，5 分享一个生活观点，6 与环境互动，7 情绪特写，8 结尾 CTA。先由角色文字锚点生成三视图、表情和服装参考，再写入角色资产库；每个 shot 自动继承 Identity Lock。",
    tags: ["虚拟达人", "角色资产", "Vlog", "一致性"],
    thumbnail: "/templates/ugc-unboxing.jpg",
    difficulty: "专业",
    deliverables: ["三视图", "表情集", "服装参考", "竖屏分镜"],
    chain: ["Character Anchor", "Reference Image Pipeline", "Identity Lock", "Storyboard"],
    variables: ["角色名", "外观", "服装", "口播主题"],
  },
  {
    id: "tmpl_education_explainer_40s",
    name: "Education Explainer 40s",
    nameZh: "知识解释短片 40s",
    category: "system",
    description: "把复杂概念拆成问题、类比、步骤和结论，适合课程和科普账号。",
    duration: "40s",
    shotCount: 9,
    shotDuration: 5,
    aspectRatio: "16:9",
    style: "clean educational explainer, elegant motion graphics, calm narration, high readability",
    workflow: "text_to_video",
    prompt:
      "制作 40 秒知识解释短片：先提出一个观众关心的问题，再用一个生活类比解释核心概念，随后拆成三步，每一步搭配一个清晰视觉隐喻，最后总结行动建议。画面要简洁，不生成大段文字；需要字幕轨和关键概念标记；Prompt Strategy 分离旁白、画面和字幕。",
    tags: ["教育", "科普", "解释器", "字幕"],
    thumbnail: "/templates/saas-explainer.jpg",
    difficulty: "入门",
    deliverables: ["旁白脚本", "视觉类比", "字幕轨", "关键帧"],
    chain: ["Prompt Decomposition", "Storyboard", "Subtitle", "Timeline"],
    variables: ["主题", "目标人群", "核心概念", "行动建议"],
  },
  {
    id: "tmpl_event_recap_60s",
    name: "Event Recap 60s",
    nameZh: "活动回顾 60s",
    category: "system",
    description: "会议、发布会、线下活动的剪辑结构：氛围、人群、演讲、互动和成果。",
    duration: "60s",
    shotCount: 12,
    shotDuration: 5,
    aspectRatio: "16:9",
    style: "event recap film, energetic but clean, polished transitions, natural crowd moments",
    workflow: "multimodal_story",
    prompt:
      "制作 60 秒活动回顾片。结构：1 场地建立，2 入场签到，3 人群和互动，4 主讲人登台，5 产品或主题亮点，6 观众反应，7 圆桌/采访，8 现场细节，9 合影或成果，10 快速 montage，11 核心数据或成果表达，12 感谢收束。需要导入实拍素材作为 video_refs，自动挑选可用镜头并标记质量风险。",
    tags: ["活动", "回顾", "企业", "多素材"],
    thumbnail: "/templates/saas-explainer.jpg",
    difficulty: "进阶",
    deliverables: ["素材筛选", "节奏剪辑", "采访片段", "60s 输出"],
    chain: ["Media Library", "Reference Stack", "Editing Agent", "Timeline", "Review"],
    variables: ["活动名", "场地", "重点人物", "交付平台"],
  },
  {
    id: "tmpl_fashion_lookbook_24s",
    name: "Fashion Lookbook 24s",
    nameZh: "时尚 Lookbook 24s",
    category: "system",
    description: "服装、配饰和美妆品牌的造型展示，强调姿态、材质和节奏。",
    duration: "24s",
    shotCount: 8,
    shotDuration: 4,
    aspectRatio: "9:16",
    style: "fashion editorial video, elegant poses, clean studio, premium fabric texture, confident pacing",
    workflow: "image_to_video",
    prompt:
      "制作 24 秒时尚 Lookbook。结构：1 主造型全身建立，2 面料微距，3 配饰特写，4 走动转身，5 第二套造型对比，6 动态姿态，7 美妆或细节，8 品牌收束。需要角色/模特参考保持脸部和身材一致；服装参考图作为 image_urls，避免颜色和版型漂移。",
    tags: ["时尚", "服装", "美妆", "角色一致性"],
    thumbnail: "/templates/ugc-unboxing.jpg",
    difficulty: "进阶",
    deliverables: ["造型分镜", "服装垫图", "姿态参考", "竖屏版本"],
    chain: ["Reference Stack", "Identity Lock", "Storyboard", "Review"],
    variables: ["品牌", "造型数量", "目标风格", "平台"],
  },
  {
    id: "tmpl_music_visualizer_45s",
    name: "Music Visualizer 45s",
    nameZh: "音乐视觉化 45s",
    category: "system",
    description: "根据音乐段落生成视觉节奏、抽象画面和表演镜头。",
    duration: "45s",
    shotCount: 9,
    shotDuration: 5,
    aspectRatio: "16:9",
    style: "music visualizer, audio reactive abstract scenes, elegant light trails, cinematic performance inserts",
    workflow: "multimodal_story",
    prompt:
      "为一段 45 秒音乐制作视觉化短片。先分析音频段落：intro、verse、drop、outro；每个段落对应不同视觉密度。镜头包含抽象粒子、表演者剪影、光轨、环境氛围和节奏切点。audio_urls 必须传入；Timeline 中标记鼓点、转场和字幕/歌词位置。",
    tags: ["音乐", "音频", "节奏", "视觉化"],
    thumbnail: "/templates/short-drama.jpg",
    difficulty: "专业",
    deliverables: ["音频节奏点", "抽象视觉", "剪辑节拍", "歌词标记"],
    chain: ["Audio Director", "Storyboard", "Timeline", "Output"],
    variables: ["音乐类型", "情绪", "是否有人物", "输出时长"],
  },
  {
    id: "tmpl_game_trailer_30s",
    name: "Game Trailer 30s",
    nameZh: "游戏预告 30s",
    category: "system",
    description: "玩法亮点、角色能力、世界观和最终爆点的高能预告结构。",
    duration: "30s",
    shotCount: 10,
    shotDuration: 4,
    aspectRatio: "16:9",
    style: "game trailer, energetic camera, readable action, cinematic UI-safe composition",
    workflow: "multimodal_story",
    prompt:
      "制作 30 秒游戏预告：1 世界观建立，2 主角能力展示，3 核心玩法循环，4 敌人或挑战，5 装备/技能升级，6 高潮战斗，7 多场景 montage，8 关键奖励，9 结尾爆点，10 标题/CTA 留白。需要角色和场景参考，动作镜头要可读，避免过快和混乱；Review Node 检查镜头信息量。",
    tags: ["游戏", "预告", "动作", "高能"],
    thumbnail: "/templates/short-drama.jpg",
    difficulty: "专业",
    deliverables: ["玩法分镜", "角色参考", "高能剪辑", "预告版"],
    chain: ["Reference Stack", "Camera Motion", "Storyboard", "Review"],
    variables: ["游戏类型", "主角", "核心玩法", "目标平台"],
  },
  {
    id: "tmpl_ecommerce_sale_15s",
    name: "Ecommerce Sale 15s",
    nameZh: "电商促销 15s",
    category: "system",
    description: "三秒抓注意、五秒讲卖点、最后明确转化动作的短促销模板。",
    duration: "15s",
    shotCount: 5,
    shotDuration: 3,
    aspectRatio: "9:16",
    style: "direct response ecommerce video, bright product lighting, clean graphic space, fast readable cuts",
    workflow: "image_to_video",
    prompt:
      "制作 15 秒电商促销短片：1 产品进入画面并给出强视觉钩子，2 展示第一个核心卖点，3 使用场景验证，4 价格/限时信息用后期字幕保留安全区域，5 CTA 收束。不要在生成画面中直接生成复杂文字；用字幕轨承载促销文案。产品图必须作为 image_urls 传入。",
    tags: ["电商", "促销", "转化", "竖屏"],
    thumbnail: "/templates/product-launch.jpg",
    difficulty: "入门",
    deliverables: ["卖点拆解", "字幕安全区", "产品垫图", "CTA"],
    chain: ["Reference Stack", "Prompt Strategy", "Subtitle", "Preflight"],
    variables: ["产品", "折扣", "卖点", "CTA"],
  },
  {
    id: "tmpl_app_store_preview_30s",
    name: "App Store Preview 30s",
    nameZh: "应用商店预览 30s",
    category: "system",
    description: "移动 App 的功能路径、使用收益和商店预览版节奏。",
    duration: "30s",
    shotCount: 7,
    shotDuration: 5,
    aspectRatio: "9:16",
    style: "mobile app preview, clean device mockups, crisp UI motion, bright white premium SaaS look",
    workflow: "multimodal_story",
    prompt:
      "制作 30 秒应用商店预览：1 用户需求，2 打开 App，3 核心功能一，4 核心功能二，5 结果页面，6 用户收益，7 下载 CTA。界面录屏或截图作为 reference video/image 输入；生成画面不能伪造 UI 文案，文字交给后期字幕和真实截图。",
    tags: ["App", "移动端", "商店预览", "界面"],
    thumbnail: "/templates/saas-explainer.jpg",
    difficulty: "进阶",
    deliverables: ["功能路径", "设备镜头", "字幕轨", "商店预览"],
    chain: ["Reference Stack", "Storyboard", "Timeline", "Output"],
    variables: ["App 名称", "功能", "目标用户", "商店平台"],
  },
  {
    id: "tmpl_customer_testimonial_35s",
    name: "Customer Testimonial 35s",
    nameZh: "客户证言 35s",
    category: "system",
    description: "B2B 案例、用户故事和转化页视频，强调可信度和结果证明。",
    duration: "35s",
    shotCount: 8,
    shotDuration: 5,
    aspectRatio: "16:9",
    style: "trustworthy customer story, documentary interview, clean b-roll, warm professional lighting",
    workflow: "multimodal_story",
    prompt:
      "制作 35 秒客户证言视频：1 客户身份建立，2 原始问题，3 采用方案，4 使用过程 B-roll，5 数据或成果，6 真实感受，7 团队协作镜头，8 总结推荐。采访素材和品牌资料作为 reference 输入；后期字幕承载关键数据，不在生成画面里伪造数字。",
    tags: ["客户案例", "B2B", "采访", "转化"],
    thumbnail: "/templates/saas-explainer.jpg",
    difficulty: "进阶",
    deliverables: ["采访结构", "B-roll", "成果字幕", "案例版本"],
    chain: ["Reference Stack", "Editing Agent", "Subtitle", "Review"],
    variables: ["客户行业", "痛点", "成果", "证言语气"],
  },
  {
    id: "tmpl_documentary_micro_30s",
    name: "Micro Documentary 30s",
    nameZh: "微纪录片 30s",
    category: "system",
    description: "人物、地点或工艺的微纪录结构，强调真实质感和节奏。",
    duration: "30s",
    shotCount: 8,
    shotDuration: 5,
    aspectRatio: "16:9",
    style: "micro documentary, natural light, observational camera, tactile details, calm pacing",
    workflow: "text_to_video",
    prompt:
      "制作 30 秒微纪录片：1 建立人物或地点，2 手部或工艺细节，3 环境声音，4 主角做一个关键动作，5 旁白解释背景，6 过程中的微小困难，7 完成结果，8 安静收束。画面重真实，不做夸张广告；Audio Director 需要记录环境音和旁白提示。",
    tags: ["纪录片", "人物", "工艺", "旁白"],
    thumbnail: "/templates/food-reel.jpg",
    difficulty: "进阶",
    deliverables: ["纪录分镜", "环境声", "旁白脚本", "质感镜头"],
    chain: ["Screenwriter", "Audio Director", "Storyboard", "Timeline"],
    variables: ["人物/地点", "工艺", "旁白风格", "情绪"],
  },
  {
    id: "tmpl_batch_ab_test_ads",
    name: "A/B Ad Variations",
    nameZh: "广告 A/B 批量测试",
    category: "system",
    description: "同一产品一次生成多版钩子、节奏和风格，用于投放前快速比较。",
    duration: "15s x 4",
    shotCount: 5,
    shotDuration: 3,
    aspectRatio: "9:16",
    style: "performance marketing variants, clear hook, fast readable cuts, product-safe composition",
    workflow: "image_to_video",
    prompt:
      "为同一产品生成四个 15 秒广告变体：A 痛点开场，B 结果开场，C 场景使用开场，D 社会证明开场。每个变体保持相同产品垫图、相同比例和相同 CTA，但镜头顺序、开场文案和节奏不同。结果以网格对比，记录版本号、变量和质量分。",
    tags: ["A/B", "批量生成", "投放", "版本"],
    thumbnail: "/templates/product-launch.jpg",
    difficulty: "专业",
    deliverables: ["4 个变体", "变量矩阵", "质量分", "投放对比"],
    chain: ["Prompt Strategy", "Batch Generate", "Version", "Review"],
    variables: ["产品", "目标受众", "钩子类型", "CTA"],
  },
];
